server:
  port: 8401

spring:
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
#        nacos 服务注册中心地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
#        sentinel dashboard 地址
        dashboard: 127.0.0.1:8080
#        默认端口
        port: 8719
  main:
    allow-circular-references: true

management:
  endpoints:
    web:
      exposure:
        include: '*'